services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    container_name: python-module

    ports:
      - "7860:7860"

    volumes:
      - .:/app

    restart: unless-stopped

    networks:
      - python-module

networks:
  python-module:
